version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Webstat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-etiir0t0ru93"
s3_prefix = "Webstat"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
