service: webstat-main

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    
functions:
  collect_stat:
    handler: bin
    events:
      - http:
          path: /v1/stat
          method: post
      