AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WebStat

Parameters:
  StatsTableName:
    Type: String
    Default: "WebstatStats"
  WhitelistedWebsite:
    Type: String
    Default: "www.ramihikmat.net"
  

Globals:
  Function:
    Timeout: 3

Resources:
  StatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref StatsTableName
      KeySchema:
        - AttributeName: Url
          KeyType: HASH
        - AttributeName: CreatedAt
          KeyType: RANGE
      AttributeDefinitions:
        -
          AttributeName: Url
          AttributeType: S
        - 
          AttributeName: CreatedAt
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      
  CollectStat:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: src
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /v1/stat
            Method: POST
            CorsConfiguration:
              AllowMethods: "'POST'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: !Ref WhitelistedWebsite
      Environment:
        Variables:
          StatsTable: !Ref StatsTableName
      Policies:
        - Version: '2012-10-17'
          Statement: 
            - Effect: 'Allow'
              Action:
                - 'dynamodb:PutItem'
              Resource: !GetAtt StatsTable.Arn
